apiVersion: v1
kind: Secret
metadata:
  name: retailerp-secrets
  namespace: retailerp
type: Opaque
stringData:
  db-connection-string: "Server=sqlserver-svc;Database=RetailERP;User Id=sa;Password=RetailERP@2024!;TrustServerCertificate=true"
  jwt-secret: "RetailERP-SuperSecret-JWT-Key-2024-Must-Be-At-Least-32-Characters"
  sa-password: "RetailERP@2024!"
  grafana-password: "admin"
