apiVersion: v1
kind: ConfigMap
metadata:
  name: retailerp-config
  namespace: retailerp
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "RetailERP.Auth"
  Jwt__Audience: "RetailERP.Client"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: retailerp
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "gateway"
        static_configs:
          - targets: ["gateway-svc:80"]
        metrics_path: /metrics
      - job_name: "auth-api"
        static_configs:
          - targets: ["auth-api-svc:80"]
        metrics_path: /metrics
      - job_name: "product-api"
        static_configs:
          - targets: ["product-api-svc:80"]
        metrics_path: /metrics
      - job_name: "inventory-api"
        static_configs:
          - targets: ["inventory-api-svc:80"]
        metrics_path: /metrics
      - job_name: "order-api"
        static_configs:
          - targets: ["order-api-svc:80"]
        metrics_path: /metrics
      - job_name: "production-api"
        static_configs:
          - targets: ["production-api-svc:80"]
        metrics_path: /metrics
      - job_name: "billing-api"
        static_configs:
          - targets: ["billing-api-svc:80"]
        metrics_path: /metrics
      - job_name: "reporting-api"
        static_configs:
          - targets: ["reporting-api-svc:80"]
        metrics_path: /metrics
