global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8080"]
    metrics_path: /metrics

  - job_name: "auth-api"
    static_configs:
      - targets: ["auth-api:8080"]
    metrics_path: /metrics

  - job_name: "product-api"
    static_configs:
      - targets: ["product-api:8080"]
    metrics_path: /metrics

  - job_name: "inventory-api"
    static_configs:
      - targets: ["inventory-api:8080"]
    metrics_path: /metrics

  - job_name: "order-api"
    static_configs:
      - targets: ["order-api:8080"]
    metrics_path: /metrics

  - job_name: "production-api"
    static_configs:
      - targets: ["production-api:8080"]
    metrics_path: /metrics

  - job_name: "billing-api"
    static_configs:
      - targets: ["billing-api:8080"]
    metrics_path: /metrics

  - job_name: "reporting-api"
    static_configs:
      - targets: ["reporting-api:8080"]
    metrics_path: /metrics
