#!/bin/bash
# ============================================================
# RetailERP — Master Test Runner
# Runs: smoke → security scan → generates report → auto-rollback if critical fail
# Usage: ./run-all-tests.sh --env prod --target docker
# ============================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
REPORT_DIR="${SCRIPT_DIR}/../reports"

ENV="dev"; TARGET="docker"; BASE_URL="http://localhost"
SMOKE_PASS=false; SECURITY_PASS=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --env)      ENV="$2"; shift 2 ;;
    --target)   TARGET="$2"; shift 2 ;;
    --base-url) BASE_URL="$2"; shift 2 ;;
    *) shift ;;
  esac
done

mkdir -p "$REPORT_DIR"
TIMESTAMP=$(date -u '+%Y%m%d-%H%M%S')

echo -e "\n${YELLOW}═══════════════════════════════════════════════${NC}"
echo -e "${YELLOW} RetailERP Full Test Suite — $ENV / $TARGET${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════${NC}\n"

# ── Phase 1: Smoke Tests ──────────────────────────────────────
echo -e "${YELLOW}[Phase 1/3] Smoke Tests${NC}"
if bash "$SCRIPT_DIR/smoke-tests.sh" --env "$ENV" --base-url "$BASE_URL"; then
  SMOKE_PASS=true
  echo -e "${GREEN}✓ Smoke tests passed${NC}"
else
  echo -e "${RED}✗ Smoke tests FAILED${NC}"
fi

# ── Phase 2: Security scan (Docker targets only) ──────────────
echo -e "\n${YELLOW}[Phase 2/3] Security Scan${NC}"
if command -v trivy &>/dev/null && [[ "$TARGET" == "docker" ]]; then
  bash "${SCRIPT_DIR}/../security/trivy-scan.sh" --env "$ENV" && SECURITY_PASS=true || \
    echo -e "${YELLOW}! Security scan completed with findings${NC}"
else
  echo -e "${YELLOW}! Skipping security scan (trivy not available or non-docker target)${NC}"
  SECURITY_PASS=true
fi

# ── Phase 3: Generate report ──────────────────────────────────
echo -e "\n${YELLOW}[Phase 3/3] Generating Report${NC}"
FINAL_STATUS="PASS"
[[ "$SMOKE_PASS" != "true" ]] && FINAL_STATUS="FAIL"

HTML_REPORT="${REPORT_DIR}/deploy-report-${ENV}-${TIMESTAMP}.html"
cat > "$HTML_REPORT" << EOF
<!DOCTYPE html>
<html>
<head>
  <title>RetailERP Deployment Report — $ENV — $TIMESTAMP</title>
  <style>
    body { font-family: -apple-system, sans-serif; max-width: 900px; margin: 2em auto; padding: 0 1em; }
    h1 { color: #1a1a2e; }
    .pass { color: #16a34a; } .fail { color: #dc2626; } .warn { color: #d97706; }
    table { width: 100%; border-collapse: collapse; margin: 1em 0; }
    th, td { padding: .6em 1em; border: 1px solid #e5e7eb; text-align: left; }
    th { background: #f9fafb; }
    .badge { padding: .2em .6em; border-radius: 4px; font-size: .85em; font-weight: bold; }
    .badge-pass { background: #dcfce7; color: #16a34a; }
    .badge-fail { background: #fee2e2; color: #dc2626; }
  </style>
</head>
<body>
  <h1>RetailERP Deployment Report</h1>
  <table>
    <tr><th>Environment</th><td>$ENV</td></tr>
    <tr><th>Target</th><td>$TARGET</td></tr>
    <tr><th>Timestamp</th><td>$(date -u '+%Y-%m-%dT%H:%M:%SZ')</td></tr>
    <tr><th>Overall Status</th><td><span class="badge badge-${FINAL_STATUS,,}">$FINAL_STATUS</span></td></tr>
  </table>
  <h2>Test Results</h2>
  <table>
    <tr><th>Phase</th><th>Result</th></tr>
    <tr><td>Smoke Tests (12 checks)</td><td class="$([ "$SMOKE_PASS" == "true" ] && echo pass || echo fail)">$([ "$SMOKE_PASS" == "true" ] && echo "✓ PASSED" || echo "✗ FAILED")</td></tr>
    <tr><td>Security Scan</td><td class="$([ "$SECURITY_PASS" == "true" ] && echo pass || echo warn)">$([ "$SECURITY_PASS" == "true" ] && echo "✓ PASSED" || echo "! WARNINGS")</td></tr>
  </table>
  <p><small>Generated by RetailERP Deployment System</small></p>
</body>
</html>
EOF
echo -e "${GREEN}✓ HTML report: $HTML_REPORT${NC}"

# ── Auto-rollback on critical failures ───────────────────────
if [[ "$SMOKE_PASS" != "true" ]]; then
  echo -e "\n${RED}✗ Critical test failures detected${NC}"

  if [[ -n "${SLACK_WEBHOOK_URL:-}" ]]; then
    curl -s -X POST "$SLACK_WEBHOOK_URL" \
      -H 'Content-type: application/json' \
      --data "{\"text\":\"🔴 RetailERP $ENV smoke tests FAILED. Triggering rollback.\"}" &>/dev/null || true
  fi

  echo -e "${YELLOW}→ Triggering rollback...${NC}"
  bash "$DEPLOY_DIR/scripts/rollback.sh" --env "$ENV" --target "$TARGET" --auto || true
  exit 1
fi

echo -e "\n${GREEN}══════════════════════════════════════════════${NC}"
echo -e "${GREEN} All Tests PASSED — $ENV deployment healthy${NC}"
echo -e "${GREEN}══════════════════════════════════════════════${NC}"

if [[ -n "${SLACK_WEBHOOK_URL:-}" ]]; then
  curl -s -X POST "$SLACK_WEBHOOK_URL" \
    -H 'Content-type: application/json' \
    --data "{\"text\":\"✅ RetailERP $ENV deployment verified — all $((SMOKE_PASS ? 12 : 0)) tests passed.\"}" &>/dev/null || true
fi
